# version: "3.8"

services:
  mongo:
    image: mongo:5.0
    container_name: mentora_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mentora_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}                      
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth-service:
    build: ./services/auth-service
    container_name: auth_service
    env_file:
      - ./services/auth-service/.env
    ports:
      - "3001:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}       # Assurez-vous que DB_PORT est défini (par défaut 3306)
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql

  user-service:
    build: ./services/user-service
    container_name: user_service
    ports:
      - "3002:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: ${DB_PORT}       # Assurez-vous que DB_PORT est défini (par défaut 3306)
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - mysql

  # course-service:
  #   build: ./services/course-service
  #   container_name: course_service
  #   ports:
  #     - "3003:3000"
  #   environment:
  #     - MONGO_URI=${MONGO_URI}
  #   depends_on:
  #     - mongo

  # roadmap-service:
  #   build: ./services/roadmap-service
  #   container_name: roadmap_service
  #   env_file:
  #     - ./services/roadmap-service/.env
  #   ports:
  #     - "3004:3000"
  #   environment:
  #     - MONGO_URI=${MONGO_URI}
  #   depends_on:
  #     - mongo

  # chatbot-service:
  #   build: ./services/chatbot-service
  #   container_name: chatbot_service
  #   env_file:
  #     - ./services/chatbot-service/.env
  #   ports:
  #     - "3005:3010"
  #   environment:
  #     # Add any required environment variables here, for example:
  #     # - PYTHON_WS_URL=ws://python-service:port
  #     # - PORT=3010
  #   depends_on:
  #     # Add dependencies if needed, e.g.:
  #     # - python-service

volumes:
  mongo_data:
  mysql_data:
